config/routes.rb
Jukebox::Application.routes.draw do

  devise_for :users

  root 'songs#index'

  get 'search', to: 'search#search', as: :search
  get 'synchronize', to: 'application#synchronize', as: :synchronize
  get 'files', to: 'application#files', as: :files
  get 'import_log', to: 'application#import_log', as: :import_log

  resources :records do
    collection do
      get :chart_data
    end
  end

  resources :artists, :types, :parameters, :playlists_songs

  resources :albums do
    member do
      get :manage
      get :add_song
      post :sort
    end
  end

  resources :users do 
   resources :playlists
  end

  resources :kinds do 
   resources :playlists
  end


  resources :songs do
    resources :records
    get :play, on: :member
    get :search, on: :collection
    post :import, on: :collection
  end

  resources :playlists do
    resources :records
    member do 
      get :play
      get :manage
      get :add_song
      post :sort
    end
  end

end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  include Concerns::Synchronize
  before_action :set_type, only: [:show, :edit, :update, :destroy]

  def index
    @types = Kaminari.paginate_array(TypeDecorator.decorate_collection(Type.all.order('name'))).page(params[:page])
  end

  def new
    @type = Type.new
  end

  def edit
  end

  def create
    @type = Type.new(type_params)

    respond_to do |format|
      if @type.save
        format.html { redirect_to types_path, notice: t('type.create', name: @type.name) }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def update
    respond_to do |format|
      if @type.update(type_params)
        format.html { redirect_to types_path, notice: t('type.update', name: @type.name) }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def destroy
  name = @type.name
    @type.destroy
      respond_to do |format|
      format.html { redirect_to types_url, notice: t('type.destroyed', name: name) }
    end
  end

  private
  def set_type
    @type = Type.find(params[:id])
  end

  def type_params
    params.require(:type).permit(:name)
  end

end

app/views/types/_form.html.haml
= simple_form_for @type, :html => {:class => 'form-horizontal'} do |f|

  .well
    = f.input :name

  .form_actions
    = f.button :submit, :class => 'btn btn-default'
    = link_to t('helpers.submit.cancel'), :back, :class => 'btn btn-default'

app/views/types/_listing.html.haml
- if types.empty?
  = t('type.empty')

- else
  .row.paginate
    .col-md-8
      = paginate types
    .col-md-4
      %p.pull-right= [types.total_count.to_s, t('model.types').downcase].join(" ")

  %table.table.table-striped
    %thead
      %tr
        %th= t('type.name')
        %th= t('type.playlists')
        %th
    %tbody
      - types.each do |type|
        %tr
          %td= type.name
          %td= type.playlists.count
          %td
            = link_to edit_type_path(type), :class => 'btn btn-default btn-sm', :title => t('type.edit') do
              %span.fa.fa-edit
            = link_to type_path(type), :class => 'btn btn-default btn-sm', :title => t('type.destroy'), method: :delete, data: { confirm: t('type.confirm_destroy') } do
              %span.fa.fa-times

app/views/types/edit.html.haml
%legend
  %h2= @type.name

= render :partial => 'form'

app/views/types/index.html.haml
.row.bar
  .col-md-8
    .title.pull-left= t('model.types')
  .col-md-4
    .btn-group.pull-right
      = link_to new_type_path, :class => 'btn btn-default', :title => t('type.new') do
        %span.fa.fa-plus

#types.partial
  = render :partial => 'listing', :locals => {:types => @types}

app/views/types/new.html.haml
%legend
  %h2= t('type.new')

= render :partial => 'form'