config/routes.rb
Jukebox::Application.routes.draw do

  devise_for :users

  root 'songs#index'

  get 'search', to: 'search#search', as: :search
  get 'synchronize', to: 'application#synchronize', as: :synchronize
  get 'files', to: 'application#files', as: :files
  get 'import_log', to: 'application#import_log', as: :import_log

  resources :records do
    collection do
      get :chart_data
    end
  end

  resources :artists, :types, :parameters, :playlists_songs

  resources :albums do
    member do
      get :manage
      get :add_song
      post :sort
    end
  end

  resources :users do 
   resources :playlists
  end

  resources :kinds do 
   resources :playlists
  end


  resources :songs do
    resources :records
    get :play, on: :member
    get :search, on: :collection
    post :import, on: :collection
  end

  resources :playlists do
    resources :records
    member do 
      get :play
      get :manage
      get :add_song
      post :sort
    end
  end

end

app/models/song.rb
class Song < ActiveRecord::Base
  include Searchable
  include Synchronizable

  mount_uploader :image, ImageUploader
  mount_uploader :file, FileUploader

  belongs_to :user
  belongs_to :artist

  has_many :playlists_songs, order: :position, dependent: :destroy
  has_many :playlists, through: :playlists_songs

  has_many :albums_songs, order: :position, dependent: :destroy
  has_many :albums, through: :albums_songs

  has_many :records, as: :recordable

  validates_presence_of :file, :name

  def details
    [decorate.albums_view, artist.name].reject(&:blank?).join(' - ')
  end

  require 'zip'
  require 'taglib'
  def self.import(tempfile, user)

    format_regex = /(\.mp3|\.mp4|\.m4a|\.wav|\.ogg|\.flac|\.wma)$/ 

    File.delete('log/import.log') if File.exist?('log/import.log')
    import_logger = Logger.new('log/import.log')

    import_logger.info "########## Starting songs import ##########"
    begin

      import_logger.info "Extracting Zip file..."
      Zip::File.open(tempfile) do |zipfile|
        zipfile.each do |f|
          zipfile.extract(f, "public/temp/#{f.name}") 
        end
      end
      import_logger.info "Zip file extracted."

      songs = Dir.entries("public/temp/").reject! {|s| ['.', '..'].include? s or format_regex.match(s).nil?}

      import_logger.info "Importing #{songs.size} song(s)"
      songs.each_with_index do |song, idx|
        begin
          import_logger.info '*'*10
          import_logger.info "Importing song n°#{idx + 1} #{song}"

          TagLib::FileRef.open("public/temp/#{song}") do |mp3|
            infos = mp3.tag
            if infos.empty?
              import_logger.error "Error importing song: no mp3 infos"
            else
              new_song = Song.new(name: infos.title.capitalize, user: user)

              new_song.duration = mp3.audio_properties.length

              new_song.artist = Artist.find_or_create_by(name: infos.artist.downcase.capitalize)

              album = Album.find_or_create_by(name: infos.album.downcase.capitalize)
            
              image = "public/temp/#{song.gsub('.mp3', '.jpg')}"
              image = image.gsub('.mp4', '.jpg')
              image = image.gsub('.m4a', '.jpg')
              image = image.gsub('.jpg', '.png') unless File.exist? image
              image = image.gsub('.png', '.jpeg') unless File.exist? image
              
              image = "public/temp/#{song}"[0..-4] + 'jpg'
              if !File.exist? image
                image = image.gsub('.jpg', '.png')
                if !File.exist? image
                  image = image.gsub('.png', '.jpeg')
                end
              end

              new_song.image = File.open(image) if File.exist? image

              new_song.file = File.open("public/temp/#{song}")

              song_exists = Song.where(name: new_song.name)

              if song_exists.empty?
                new_song.save! 
                new_song.albums << album
                import_logger.info "Saving song: #{new_song.name}"
              else
                import_logger.info "Song already exists" 
              end
            end
          end
        rescue => e
          import_logger.error "Error importing song: #{e}"
          next
        end
      end
    rescue Exception => e
      import_logger.error "*************** Error importing songs"
      import_logger.error "Trace: #{e.backtrace}"
      import_logger.error "***************"
    end
    FileUtils.rm_rf(Dir.glob('public/temp/*'))
    import_logger.info "########## Finished songs import ##########"
  end

  end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  include Concerns::Synchronize
  before_action :set_song, only: [:play, :show, :edit, :update, :destroy]
  before_action :fix_duration_params, only: [:create, :update]

  def index
    @songs = Kaminari.paginate_array(SongDecorator.decorate_collection(Song.all.order('name'))).page(params[:page])
  end

  def show
    @song = @song.decorate
  end

  def import
    Song.import(params[:import][:file].tempfile, current_user)
    songs = Kaminari.paginate_array(SongDecorator.decorate_collection(Song.all)).page(params[:page])
    render partial: 'listing', locals: {songs: songs} 
  end

  def play
    artist = @song.artist.nil? ? "" : @song.artist.name
    song_data = {title: @song.name, artist: artist, mp3: @song.file.url, poster: @song.image.url}
    render json: song_data.to_json
  end

  def search
    q = "%#{params[:q]}%"
    songs = Song.where("name like ? or artist_id in (select id from artists where name like ? )", q, q)
    songs.collect! {|s| {artist: (s.artist.nil? ? "" : s.artist.name), album: s.decorate.albums_view, img: s.image.url(:thumb), title: s.name, song_id: s.id}}
    render json: songs.to_json
  end

  def new
    @song = Song.new
  end

  def edit
  end

  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: t('song.create', name: @song.name) }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: t('song.update', name: @song.name) }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def destroy
  name = @song.name
    @song.destroy
      respond_to do |format|
      format.html { redirect_to songs_url, notice: t('song.destroyed', name: name) }
    end
  end

  private
  def set_song
    @song = Song.find(params[:id])
  end

  def song_params
    params.require(:song).permit(:name, :image, :file, :artist_id, :duration, :user_id, playlist_ids: [], album_ids: [])
  end

  def fix_duration_params
    unless params[:song][:duration].empty?
      time = Time.parse("00:#{params[:song][:duration]}")
      duration = time.min*60 + time.sec
      params[:song].merge!({'duration' => duration})
    end
  end

end

app/views/songs/_form.html.haml
= simple_form_for @song, :html => {:class => 'form-horizontal', :multipart => true} do |f|

  .well
    = f.input :name
    = f.input :artist_id, collection: artists, selected: (@song.artist.id unless @song.artist.nil?), prompt: t('helpers.words.choose'), as: :with_link
    = f.input :duration, as: :duration
    = f.association :playlists, collection: playlists, as: :with_link, input_html: { multiple: 'multiple' }
    = f.association :albums, collection: albums, as: :with_link, input_html: { multiple: 'multiple' }
    = f.input :image 
    = f.input :file
    = f.input :user_id, as: :hidden, input_html: { value: current_user.id }

  .form_actions
    = f.button :submit, :class => 'btn btn-default'
    = link_to t('helpers.submit.cancel'), :back, :class => 'btn btn-default'

app/views/songs/_listing.html.haml
- if songs.empty?
  = t('song.empty')

- else

  .row.paginate
    .col-md-8
      = paginate songs
    .col-md-4
      %p.pull-right= [songs.total_count.to_s, t('model.songs').downcase].join(" ")

  %table.table.table-striped
    %thead
      %tr
        %th
        %th= t('song.name')
        %th= t('song.artist_id')
        %th= t('song.albums')
        %th
    %tbody
      - songs.each do |song|
        %tr
          %td.img= image_tag song.image_url(:thumb)
          %td= song.name
          %td= song.artist
          %td= song.albums
          %td
            .row
              = link_to play_song_path(song), class: 'btn btn-default btn-sm play', title: t('helpers.words.play'), src: song.file.url do
                %span.fa.fa-play
              = link_to '#', class: 'btn btn-default btn-sm pause', title: t('helpers.words.pause') do
                %span.fa.fa-pause
              = link_to song, class: 'btn btn-default btn-sm', title: t('song.show') do
                %span.fa.fa-eye
            .row
              = link_to edit_song_path(song), class: 'btn btn-default btn-sm', title: t('song.edit') do
                %span.fa.fa-edit
              = link_to song_path(song), class: 'btn btn-default btn-sm', title: t('song.destroy'), method: :delete, data: { confirm: t('song.confirm_destroy') } do
                %span.fa.fa-times

app/views/songs/edit.html.haml
%legend
  %h2= @song.name

= render :partial => 'form'

app/views/songs/index.html.haml
.row.bar
  .col-md-8
    .title.pull-left= t('model.songs')
  .col-md-4
    .btn-group.pull-right
      = link_to new_song_path, :class => 'btn btn-default', :title => t('song.new') do
        %span.fa.fa-plus
      = link_to '#', :class => 'btn btn-default import_btn', title: t('song.import') do
        %span.fa.fa-download
      = link_to import_log_path, :class => 'btn btn-default', :title => t('song.import_log') do
        %span.fa.fa-file-text
      = form_for :import, url: import_songs_path, remote: true, html: { id: 'import_form' } do |f|
        = f.file_field 'file', accept: '.zip', style: 'display:none'

#songs.partial
  = render :partial => 'listing', :locals => {:songs => @songs}

- content_for :player do
  = render :partial => 'player'

app/views/songs/new.html.haml
%legend
  %h2= t('song.new')

= render :partial => 'form'

app/views/songs/show.html.haml
%legend.row
  %h2.pull-left= @song.name
  .btn-group.pull-right
    = link_to edit_song_path(@song), class: 'btn btn-default', title: t('song.edit') do
      %span.fa.fa-edit
    = link_to song_path(@song), class: 'btn btn-default', title: t('song.destroy'), method: :delete, data: { confirm: t('song.confirm_destroy') } do
      %span.fa.fa-trash-o


.row
  .col-md-3
    = link_to '#', class: 'thumbnail' do
      = image_tag @song.image_url

  .col-md-9
    .well
      %dl.dl-horizontal
        %dt= t('song.name')
        %dd= @song.name
        %dt= t('song.artist_id')
        %dd= @song.artist
        %dt= t('song.albums')
        %dd= @song.albums
        %dt= t('song.user')
        %dd= @song.user
        %dt= t('song.duration')
        %dd= @song.duration
        %dt= t('song.file')
        %dd= @song.file
        %dt= t('song.created_at')
        %dd= @song.created_at

= link_to t('helpers.submit.back'), :back, :class => 'btn btn-default'