config/routes.rb
Jukebox::Application.routes.draw do

  devise_for :users

  root 'songs#index'

  get 'search', to: 'search#search', as: :search
  get 'synchronize', to: 'application#synchronize', as: :synchronize
  get 'files', to: 'application#files', as: :files
  get 'import_log', to: 'application#import_log', as: :import_log

  resources :records do
    collection do
      get :chart_data
    end
  end

  resources :artists, :types, :parameters, :playlists_songs

  resources :albums do
    member do
      get :manage
      get :add_song
      post :sort
    end
  end

  resources :users do 
   resources :playlists
  end

  resources :kinds do 
   resources :playlists
  end


  resources :songs do
    resources :records
    get :play, on: :member
    get :search, on: :collection
    post :import, on: :collection
  end

  resources :playlists do
    resources :records
    member do 
      get :play
      get :manage
      get :add_song
      post :sort
    end
  end

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  include Searchable

  mount_uploader :image, ImageUploader

  belongs_to :user

  has_many :kinds_playlists
  has_many :kinds, :through => :kinds_playlists

  has_many :playlists_songs, order: :position, dependent: :destroy
  has_many :songs, through: :playlists_songs

  has_many :playlists_types, dependent: :destroy
  has_many :types, through: :playlists_types

  has_many :records, as: :recordable

  validates_presence_of :name

  def add_song(song_id)
    ps = PlaylistsSong.new(playlist_id: self.id, song_id: song_id)
    ps.save!
  end

  def details
    ["#{songs.count} titre(s)", decorate.types_view].reject(&:blank?).join(' - ')
  end

  def self.updated(date)
    results = where('updated_at > ? and published is true', date)
  end

  require 'zip'
  #require 'mp3info'
  def self.import(tempfile, user)
    begin
      temp_path = 'public/temp'

      # Extract directories (structure)
      Zip::File.open(tempfile) do |zipfile|
        zipfile.each do |f|
          FileUtils.mkpath("#{temp_path}/#{f.name}") if f.directory? and !File.directory? f.name
        end
      end

      # Extract files
      Zip::File.open(tempfile) do |zipfile|
        zipfile.each do |f|
          zipfile.extract(f, "#{temp_path}/#{f.name}") unless f.directory?
        end
      end

      # Getting each playlist from extacted files
      playlists = Dir.entries(temp_path).reject! {|p| p.include? '.'}

      playlists.each do |p|
        path = "#{temp_path}/#{p}/"
        playlist = Playlist.new(user: user)

        # Retrieve infos.txt + playlist image + songs
        infos = File.open("#{path}infos.txt").read
        img = File.open("#{path}img.jpg")
        songs = Dir.entries("#{path}songs/").reject! {|s| ['.', '..'].include? s or s.include? '.jpg'}
        images = Dir.entries("#{path}songs/").reject! {|s| ['.', '..'].include? s or s.include? '.mp3'}

        # Reading playlist infos from infos.txt + assign kinds to playlist
        infos.each_line.with_index do |line, idx|
          if idx == 0
            playlist.name = line.capitalize 
          elsif idx == 1
            kinds = line.split(';').collect {|k| k.squish.capitalize}
            kinds = kinds.collect {|kind| Kind.find_or_create_by(name: kind)}
            kinds.each {|kind| KindsPlaylist.create(kind: kind, playlist: playlist)}
          else 
            break
          end
        end

        # Affect image to playlist
        playlist.image = img

        songs.each do |song|
          #mp3 = Mp3Info.open("#{path}songs/#{song}") 
          mp3 = ""
          infos = mp3.tag.empty? ? mp3.tag1 : mp3.tag
          unless infos.empty?
            new_song = Song.new(name: infos.title.capitalize, album: infos.album.capitalize, user: user)

            new_song.artist = Artist.find_or_create_by(name: infos.artist.downcase)

            image = "#{path}songs/#{song.gsub('.mp3', '.jpg')}"
            new_song.image = File.exist?(image) ? File.open(image) : infos.image

            new_song.file = File.open("#{path}songs/#{song}")

            song_exists = Song.where(name: new_song.name, artist: new_song.artist, album: new_song.album)
            if song_exists.empty?
              new_song.save! 
            else
              new_song = song_exists.first
            end

            PlaylistsSong.create(playlist_id: playlist.id, song_id: new_song.id) 
          end
        end
        playlist.save!
      end
    rescue Exception => e
    end
    FileUtils.rm_rf(Dir.glob('public/temp/*'))
  end

end

app/models/playlists_type.rb
class PlaylistsType < ActiveRecord::Base
  include Synchronizable

  belongs_to :playlist
  belongs_to :type
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  include Concerns::Synchronize
  before_action :set_playlist, only: [:add_song, :sort, :manage, :play, :show, :edit, :update, :destroy]

  def index
    @playlists = Kaminari.paginate_array(PlaylistDecorator.decorate_collection(Playlist.all.order('name'))).page(params[:page])
  end

  def import
    Playlist.import(params[:import][:file].tempfile, current_user)
    render partial: 'listing', locals: {playlists: PlaylistDecorator.decorate_collection(Playlist.all)}
  end

  def add_song
    song = Song.find(params[:song_id])
    ps = @playlist.add_song(params[:song_id]) 
    render partial: 'song', locals: {song: song, playlists_song: ps}
  end

  def play
    songs_data = @playlist.songs.order('position asc').collect {|s| {title: s.name, artist: s.artist, mp3: s.file.url}}
    render json: songs_data.to_json
  end

  def sort
    @playlist_songs = PlaylistsSong.where(:playlist_id => @playlist.id, :song_id => params[:song])
    @playlist_songs.each do |ps|
      ps.position = params['song'].index(ps.song.id.to_s) + 1
      ps.save
    end
    render :nothing => true
  end

  def manage
  end

  def show
    @playlist = @playlist.decorate
  end

  def new
    @playlist = Playlist.new
  end

  def edit
  end

  def create
    @playlist = Playlist.new(playlist_params)

    respond_to do |format|
      if @playlist.save
        format.html { redirect_to manage_playlist_path(@playlist), notice: t('playlist.create', name: @playlist.name) }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def update
    respond_to do |format|
      if @playlist.update(playlist_params)
        format.html { redirect_to @playlist, notice: t('playlist.update', name: @playlist.name) }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def destroy
    name = @playlist.name
    @playlist.destroy
      respond_to do |format|
      format.html { redirect_to playlists_url, notice: t('playlist.destroyed', name: name) }
    end
  end

  private
  def set_playlist
    @playlist = Playlist.find(params[:id])
  end

  def playlist_params
    params.require(:playlist).permit(:name, :image, :description, :published, :kind_id, :user_id, song_ids: [], kind_ids: [], type_ids: [])
  end

end

app/views/playlists/_form.html.haml
= simple_form_for @playlist, :html => {:class => 'form-horizontal'} do |f|

  .well
    = f.input :name
    = f.association :kinds, collection: kinds, as: :with_link, input_html: {multiple: 'multiple'}
    = f.association :types, collection: types, as: :with_link, input_html: {multiple: 'multiple'}
    = f.input :image
    = f.input :description
    = f.input :published
    = f.input :user_id, as: :hidden, input_html: { value: current_user.id }

  .form_actions
    = f.button :submit, :class => 'btn btn-default'
    = link_to t('helpers.submit.cancel'), :back, :class => 'btn btn-default'

app/views/playlists/_listing.html.haml
- if playlists.empty?
  = t('playlist.empty')

- else
  .row.paginate
    .col-md-8
      = paginate playlists
    .col-md-4
      %p.pull-right= [playlists.total_count.to_s, t('model.playlists').downcase].join(" ")

  %table.table.table-striped
    %thead
      %tr
        %th
        %th= t('playlist.name')
        %th= t('playlist.types')
        %th= t('playlist.published')
        %th= t('playlist.songs')
        %th
    %tbody
      - playlists.each do |playlist|
        %tr
          %td.img= image_tag playlist.image_url(:thumb)
          %td= playlist.name
          %td= playlist.types
          %td= playlist.published
          %td= playlist.songs.size
          %td
            .row
              = link_to play_playlist_path(playlist), :class => 'btn btn-default btn-sm play', :title => t('helpers.words.play') do
                %span.fa.fa-play
              = link_to '#', :class => 'btn btn-default btn-sm pause', :title => t('helpers.words.pause') do
                %span.fa.fa-pause
              = link_to playlist, class: 'btn btn-default btn-sm', title: t('playlist.show') do
                %span.fa.fa-eye
              = link_to manage_playlist_path(playlist), :class => 'btn btn-default btn-sm', :title => t('playlist.manage') do
                %span.fa.fa-music
            .row
              = link_to edit_playlist_path(playlist), :class => 'btn btn-default btn-sm', :title => t('playlist.edit') do
                %span.fa.fa-edit
              = link_to playlist_path(playlist), :class => 'btn btn-default btn-sm', :title => t('playlist.destroy'), method: :delete, data: { confirm: t('playlist.confirm_destroy') } do
                %span.fa.fa-times

app/views/playlists/_player.html.haml
#jp_container_1.jp-video
  .jp-type-playlist
    #jquery_jplayer_1.jp-jplayer
    .jp-gui
      .jp-video-play
        = link_to 'javascript:;', 'play', :class => 'jp-video-play-icon', :tabiindex => '1'
      .jp-interface
        .jp-progress
          .jp-seek-bar
            .jp-play-bar
        .jp-current-time
        .jp-duration
        .jp-controls-holder
          %ul.jp-controls
            %li= link_to 'javascript:;', 'previous', :class => 'jp-previous', :tabindex => '1'
            %li= link_to 'javascript:;', 'play', :class => 'jp-play', :tabindex => '1'
            %li= link_to 'javascript:;', 'pause', :class => 'jp-pause', :tabindex => '1'
            %li= link_to 'javascript:;', 'next', :class => 'jp-next', :tabindex => '1'
            %li= link_to 'javascript:;', 'stop', :class => 'jp-stop', :tabindex => '1'
            %li= link_to 'javascript:;', 'mute', :class => 'jp-mute', :tabindex => '1', :title => 'mute'
            %li= link_to 'javascript:;', 'unmute', :class => 'jp-unmute', :tabindex => '1', :title => 'unmute'
            %li= link_to 'javascript:;', 'max volume', :class => 'jp-volume-max', :tabindex => '1', :title => 'max volume'
          .jp-volume-bar
            .jp-volume-bar-value
          %ul.jp-toggles
            %li= link_to 'javascript:;', 'full screen', :class => 'jp-full-screen', :tabindex => '1', :title => 'full screen'
            %li= link_to 'javascript:;', 'restore screen', :class => 'jp-restore-screen', :tabindex => '1', :title => 'restore screen'
            %li= link_to 'javascript:;', 'shuffle', :class => 'jp-shuffle', :tabindex => '1', :title => 'shuffle'
            %li= link_to 'javascript:;', 'shuffle off', :class => 'jp-shuffle-off', :tabindex => '1', :title => 'shuffle pff', :style => 'display:none'
            %li= link_to 'javascript:;', 'repeat', :class => 'jp-repeat', :tabindex => '1', :title => 'repeat'
            %li= link_to 'javascript:;', 'repeat off', :class => 'jp-repeat-off', :tabindex => '1', :title => 'repeat pff'
        .jp-title
          %ul
            %li 
    .jp-no-solution
      %span Update Required
      To play the media you will need to either update your browser to a recent version or update your
      = succeed "." do
        %a{href: "http://get.adobe.com/flashplayer/", target: "_blank"} Flash plugin

app/views/playlists/_song.html.haml
%li.media.handle{id: "song_#{song.id}"}
  = link_to '#', class: 'pull-left' do
    = image_tag song.image_url(:thumb)
  .media-body
    %h4.media-heading= song.name
    = song.decorate.artist
    %br
    = song.decorate.albums
  .media-actions
    = link_to edit_song_path(song), class: 'btn btn-default', title: t('song.edit') do
      %span.fa.fa-edit
    = link_to playlists_song_path(playlists_song), method: :delete, remote: true, class: 'btn btn-default delete_song', title: t('playlist.new') do
      %span.fa.fa-trash-o

app/views/playlists/edit.html.haml
%legend
  %h2= @playlist.name

= render :partial => 'form'

app/views/playlists/index.html.haml
.row.bar
  .col-md-8
    .title.pull-left= t('model.playlists')
  .col-md-4
    .btn-group.pull-right
      = link_to new_playlist_path, :class => 'btn btn-default', :title => t('playlist.new') do
        %span.fa.fa-plus

#playlists.partial
  = render :partial => 'listing', :locals => {:playlists => @playlists}

- content_for :player do
  = render :partial => 'player'

app/views/playlists/manage.html.haml
%legend
  %h2= @playlist.name

.well.search
  .col-lg-12
    = text_field_tag :q, nil, :placeholder => t('song.search'), :class => 'form-control search_songs'

%ul.media-list#sortable_songs{url: sort_playlist_path(@playlist)}
  - @playlist.playlists_songs.each do |ps|
    = render partial: 'song', locals: {song: ps.song, playlists_song: ps}

= link_to t('helpers.submit.back'), :back, :class => 'btn btn-default'

app/views/playlists/new.html.haml
%legend
  %h2= t('playlist.new')

= render :partial => 'form'

app/views/playlists/show.html.haml
%legend.row
  %h2.pull-left= @playlist.name
  .btn-group.pull-right
    = link_to manage_playlist_path(@playlist), :class => 'btn btn-default', :title => t('playlist.manage') do
      %span.fa.fa-music
    = link_to edit_playlist_path(@playlist), class: 'btn btn-default', title: t('playlist.edit') do
      %span.fa.fa-edit
    = link_to playlist_path(@playlist), class: 'btn btn-default', title: t('playlist.destroy'), method: :delete, data: { confirm: t('playlist.confirm_destroy') } do
      %span.fa.fa-trash-o


.row
  .col-md-3
    = link_to '#', class: 'thumbnail' do
      = image_tag @playlist.image_url

  .col-md-9
    .well
      %dl.dl-horizontal
        %dt= t('playlist.name')
        %dd= @playlist.name
        %dt= t('playlist.description')
        %dd= @playlist.description
        %dt= t('playlist.user')
        %dd= @playlist.user
        %dt= t('playlist.kinds')
        %dd= @playlist.kinds
        %dt= t('playlist.types')
        %dd= @playlist.types
        %dt= t('playlist.songs')
        %dd= @playlist.songs.count
        %dt= t('records.listened')
        %dd= @playlist.records.count
        %dt= t('playlist.published')
        %dd= @playlist.published

= link_to t('helpers.submit.back'), :back, :class => 'btn btn-default'