config/routes.rb
Jukebox::Application.routes.draw do

  devise_for :users

  root 'songs#index'

  get 'search', to: 'search#search', as: :search
  get 'synchronize', to: 'application#synchronize', as: :synchronize
  get 'files', to: 'application#files', as: :files
  get 'import_log', to: 'application#import_log', as: :import_log

  resources :records do
    collection do
      get :chart_data
    end
  end

  resources :artists, :types, :parameters, :playlists_songs

  resources :albums do
    member do
      get :manage
      get :add_song
      post :sort
    end
  end

  resources :users do 
   resources :playlists
  end

  resources :kinds do 
   resources :playlists
  end


  resources :songs do
    resources :records
    get :play, on: :member
    get :search, on: :collection
    post :import, on: :collection
  end

  resources :playlists do
    resources :records
    member do 
      get :play
      get :manage
      get :add_song
      post :sort
    end
  end

end

app/models/parameter.rb
class Parameter < ActiveRecord::Base
  include Synchronizable

  validates :name, uniqueness: true
  validates_presence_of :name, :value
end

app/controllers/parameters_controller.rb
class ParametersController < ApplicationController
  include Concerns::Synchronize
  before_action :set_parameter, only: [:show, :edit, :update, :destroy]

  def index
    @parameters = Kaminari.paginate_array(ParameterDecorator.decorate_collection(Parameter.all)).page(params[:page])
  end

  def new
    @parameter = Parameter.new
  end

  def edit
  end

  def create
    @parameter = Parameter.new(parameter_params)

    respond_to do |format|
      if @parameter.save
        format.html { redirect_to parameters_path, notice: t('parameter.create', name: @parameter.name) }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def update
    respond_to do |format|
      if @parameter.update(parameter_params)
        format.html { redirect_to parameters_path, notice: t('parameter.update', name: @parameter.name) }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def destroy
  name = @parameter.name
    @parameter.destroy
      respond_to do |format|
      format.html { redirect_to parameters_url, notice: t('parameter.destroyed', name: name) }
    end
  end

  private
  def set_parameter
    @parameter = Parameter.find(params[:id])
  end

  def parameter_params
    params.require(:parameter).permit(:name, :value)
  end

end

app/views/parameters/_form.html.haml
= simple_form_for @parameter, :html => {:class => 'form-horizontal'} do |f|

  .well
    = f.input :name
    = f.input :value

  .form_actions
    = f.button :submit, :class => 'btn btn-default'
    = link_to t('helpers.submit.cancel'), :back, :class => 'btn btn-default'

app/views/parameters/_listing.html.haml
- if parameters.empty?
  = t('parameter.empty')

- else
  .row.paginate
    .col-md-8
      = paginate parameters
    .col-md-4
      %p.pull-right= [parameters.total_count.to_s, t('model.parameters').downcase].join(" ")

  %table.table.table-striped
    %thead
      %tr
        %th= t('parameter.name')
        %th= t('parameter.value')
        %th
    %tbody
      - parameters.each do |parameter|
        %tr
          %td= parameter.name
          %td= parameter.value
          %td
            = link_to edit_parameter_path(parameter), :class => 'btn btn-default btn-sm', :title => t('parameter.edit') do
              %span.fa.fa-edit
            = link_to parameter_path(parameter), :class => 'btn btn-default btn-sm', :title => t('parameter.destroy'), method: :delete, data: { confirm: t('parameter.confirm_destroy') } do
              %span.fa.fa-times

app/views/parameters/edit.html.haml
%legend
  %h2= @parameter.name

= render :partial => 'form'

app/views/parameters/index.html.haml
.row.bar
  .col-md-8
    .title.pull-left= t('model.parameters')
  .col-md-4
    .btn-group.pull-right
      = link_to new_parameter_path, :class => 'btn btn-default', :title => t('parameter.new') do
        %span.fa.fa-plus

#parameters.partial
  = render :partial => 'listing', :locals => {:parameters => @parameters}

app/views/parameters/new.html.haml
%legend
  %h2= t('parameter.new')

= render :partial => 'form'